from tests.schrodinger.test_ligprep import *
from tests.schrodinger.test_glide import *
from tests.schrodinger.test_macromodel import *
from tests.schrodinger.test_fep_plus_setup import *
from tests.schrodinger.test_fep_plus_execution import *
from tests.schrodinger.test_fep_analysis import *
from tests.schrodinger.test_prepwizard import *
from tests.schrodinger.test_prime import *
from tests.schrodinger.test_desmond_production import *
from tests.schrodinger.test_desmond_setup import *
